[package]
name = "browser"
version = "0.1.0"
authors = ["Ulf Lilleengen <lulf@redhat.com>"]
edition = "2018"
description = "WebAssembly using Drogue Device"
keywords = ["wasm"]

[workspace]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
embedded-hal = { version = "0.2", features = ["unproven"] }
wasm-logger = "0.2.0"
log = "0.4"

drogue-device = { path = "../../../device", features = ["log"], default-features = false }
web-embedded-hal = "0.1.0"
embassy-executor = { version = "0.1.0", default-features = false, features = ["wasm", "executor-agnostic", "nightly", "unstable-traits"] }
ector = { version = "0.1.0", default-features = false }

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"

[patch.crates-io]
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "ba67f6d3a8c84262fcc9b2020670515d192555f1" }
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git", rev = "ba67f6d3a8c84262fcc9b2020670515d192555f1" }
embassy-hal-common = { git = "https://github.com/embassy-rs/embassy.git", rev = "ba67f6d3a8c84262fcc9b2020670515d192555f1" }
ector = { git = "https://github.com/drogue-iot/ector.git", rev = "63c08489da17ff92c493f21411411ce5ddd6154a" }

#embassy-executor = { path = "../../../../../embassy/embassy" }
