[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>",
    "Jens Reimann <jreimann@redhat.com>",
    "Dejan Bosanac <dbosanac@redhat.com>"
]
edition = "2018"
name = "iot02a-blinky"
version = "0.1.0"
resolver = "2"
description = "STM32 IoT Discovery board blinky"
keywords = ["stm32u5", "basic"]

[dependencies]

defmt = "0.3"
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }

drogue-device = { path = "../../../../device", default-features = false, features = ["defmt", "time", "bsp+b_u585i_iot02a"] }
cortex-m-rt = "0.7"
cortex-m = "0.7"

drogue-blinky-app = { path = "../../../apps/blinky" }
embedded-tls = { version = "0.8.0", default-features = false, features = ["async", "defmt"], optional = true}
cfg-if = "1.0.0"

atomic-polyfill = "0.1"
embassy-executor = { version = "0.1.0", default-features = false, features=["defmt", "time", "time-tick-32768hz"] }
embassy-stm32 = {version = "0.1.0", default-features = false, features = ["defmt", "time-driver-any", "memory-x"] }
#drogue-temperature = { path = "../../../apps/temperature", features = ["defmt"] }

embedded-hal = { version = "0.2.4", features = ["unproven"] }

[features]
default = [
    "b-u585i-iot02a",
]
tls = ["embedded-tls", "embedded-tls/defmt", "drogue-device/tls"]
b-u585i-iot02a = ["embassy-stm32/stm32u585ai"]

