[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "esp8266"
version = "0.1.0"
description = "Example using a USB-to-Serial adapter + ESP8266 adapter"
keywords = ["std", "wifi", "networking", "cloud"]

[dependencies]
log = "0.4"
env_logger = "0.8"
drogue-device = { path = "../../../device", features = ["log", "std", "wifi+esp8266"] }
embedded-tls = { version = "0.8.0", default-features = false, features = ["async"], optional = true}
embedded-io = { version = "0.3.0", features = ["async", "std", "futures"] }
#drogue-tls = {path = "../../drogue-tls", default-features = false, optional = true}

embassy-executor = { version = "0.1.0", default-features = false, features = ["std"] }
rand = "0.8"
cfg-if = "1.0.0"

embedded-hal = {version = "0.2.4", features = ["unproven"] }
embedded-hal-async = { version = "0.1.0-alpha.1" }
drogue-temperature = { path = "../../apps/temperature" }

async-io = "1.6.0"
nix = "0.22.1"
futures = { version = "0.3.17" }
libc = "0.2.101"

[features]
tls = ["embedded-tls", "embedded-tls/log", "drogue-device/tls", "drogue-temperature/tls"]
default = ["tls"]
