[package]
authors = [
    "Ulf Lilleengen <lulf@redhat.com>",
    "Bob McWhirter <bmcwhirt@redhat.com>"
]
edition = "2018"
name = "nucleo-h743zi_epd"
version = "0.1.0"
description = "STM32 Nucleo-H743 7-color e-paper display"
keywords = ["spi", "stm32h7", "epd", "display"]
resolver = "2"

[dependencies]
defmt = "0.3"
defmt-rtt = "0.3"
panic-probe = { version = "0.3", features = ["print-defmt"] }

embedded-hal = { version = "0.2.4", features = ["unproven"] }
drogue-device = { path = "../../../../device", features = ["defmt"], default-features = false }
ector = { version = "0.1.0", default-features = false }
cortex-m-rt = "0.7"
cortex-m = { version = "0.7", features = ["inline-asm"] }
heapless = { version = "0.7.1", default-features = false }
void = { version = "1", default-features = false }
embedded-graphics = { version = "0.7.1" }
embedded-graphics-core = { version = "0.3.2" }
epd-waveshare = { git = "https://github.com/Caemor/epd-waveshare.git", features = [ "graphics"] }
tinybmp = "0.3.1"

embassy-executor = { version = "0.1.0", default-features = false, features = ["time-tick-32768hz"] }
embassy-stm32 = { version = "0.1.0", default-features = false, features = ["stm32h743zi", "defmt", "memory-x", "time-driver-any", "exti", "nightly", "unstable-traits"] }
